language: generic
sudo: required
dist: trusty
services:
  - docker
before_install:
  # Install git-lfs
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.5.4/git-lfs-linux-amd64-1.5.4.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.5.4.tar.gz
  - mv git-lfs-1.5.4/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
  # Restore docker image cache
  - if [[ -f docker/ut-notebooks.tar ]]; then docker load < docker/ut-notebooks.tar; fi
before_script:
  - git lfs pull
  - bash reset_timestamps.sh
script:
  - docker-compose run latex make
before_cache:
  # Save docker image as a cache
  - if [[ ! -f docker/ut-notebooks.tar ]]; then mkdir -p docker && docker save hakatashi/ut-notebooks > docker/ut-notebooks.tar; fi
cache:
  directories:
    - dist
    - docker
deploy:
  provider: s3
  local_dir: dist
  access_key_id: AKIAIUVOWRPPIGFZXQVA
  secret_access_key:
    secure: sVJ/TuTZJxM9lR2PZJtxHf0XnNR21I9ywcEh+7+hqmedQpbgI1tgfqgs5sHypC8trGuPNO0AkrvRa9qg55iSfNo30ClKJqQ6gZjhd6rxYa1WrFooFNHtiW4Pzacw9byWlfs1Uod/hgdCaOOL2vRIGUp6gAoGu+uEPpQ5OmUJRgG8QyDeAGcm9EEAYWgZtA5zvbfSGuKvGMYUM7NqJ2upQNvjkxdRIUvCISZ8R91IDzZVQlNn6OVAESLTHLvm6ug2wBURxNR8WIV8G28EC50oe+SWjR1CEXxFWKydaxThQ4LMRimST4IM9qgqarFs057u5dOp8Wf8h+9sQhRv4hK4U68WbxmSJ4RBY7YbkwYQK/vdTA+y6KMcMVi/Yi7HHmo5V4+fXmVaBwFpX+RqXzvR1F3E4lDm74nRoiK1RzxGszPiX+W3TAR/U4Mu3H4ZyJoJPj4ySZ5hF+M5gX39wpWUkcT9z5frDGacFTkjytOYRt6KhdBEeK6+IbpQaFLv5K6dyd0vA42maidIofanIsBEwWtFL/HEXq/8pSJGtjNZZYhpLquCZsuMN4fst5Zed58Le1KpYpOpIPaDzzLqgXcVofORejwCvtSgc3hPXp2DEMnQzK2EJtmRYdAWUVCQEBvmWQ5Wsr4y5no8RY1kMasWgper56wWrGV1FHhdJXjYbh0=
  bucket: ut-notebooks
  acl: public_read
  region: ap-northeast-1
  skip_cleanup: true
  on:
    repo: hakatashi/UT-notebooks
    branch: master
notifications:
  webhooks: http://webhook.hakatashi.com/travis
